name: Test and Release Go CLI

on: [push]

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: true
      - name: Execute the tests
        run: go test -race ./...

  releases:
    needs: tests
    name: GoReleaser Build on All OS but Windows
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0

  releases-windows:
    needs: tests
    name: GoReleaser Build on Windows
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --config .goreleaser-windows.yaml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
